import Head from 'next/head';

import styles from '../styles/Home.module.css';

import Header from '../components/header/header';
import HeroSection from '../components/hero-section/hero-section';
import Reasons from '../components/resasons/reasons';
import AboutUs from '../components/about-us/about-us';
import Services from '../components/services/services';
import Stats from '../components/stats/stats';
import Ads from '../components/ads/ads';
import Projects from '../components/projects/projects';
import Cta from '../components/cta/cta';
import Footer from '../components/footer/footer';
import Bottom from '../components/bottom/bottom';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The box - Real estate company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <HeroSection />
      <Reasons />
      <AboutUs />
      <Services />
      <Stats />
      <Ads />
      <Projects />
      <Cta />
      <Footer />
      <Bottom />
    </div>
  )
}
